title: "AB Satyaprakash"
email: absatyaprakash01@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Find all the awesome projects I worked on as a part of my MLH Fellowship 
  in Fall 2020 here!
baseurl: "/" 
url: "/MLHPortfolio" 
twitter_username: AbSatyaprakash
github_username:  imperial-lord

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg